//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollector.Client.Translation {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DataCollector.Client.Translation.Strings", typeof(Strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accelerometer.
        /// </summary>
        internal static string Accelerometer {
            get {
                return ResourceManager.GetString("Accelerometer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Administrator.
        /// </summary>
        internal static string Administrator {
            get {
                return ResourceManager.GetString("Administrator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Air pressure.
        /// </summary>
        internal static string AirPressure {
            get {
                return ResourceManager.GetString("AirPressure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allowed range: {0}-{1}.
        /// </summary>
        internal static string AllowedRange {
            get {
                return ResourceManager.GetString("AllowedRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application.
        /// </summary>
        internal static string Application {
            get {
                return ResourceManager.GetString("Application", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The authorization is required.
        /// </summary>
        internal static string AuthorizationRequired {
            get {
                return ResourceManager.GetString("AuthorizationRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average.
        /// </summary>
        internal static string Average {
            get {
                return ResourceManager.GetString("Average", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string Cancel {
            get {
                return ResourceManager.GetString("Cancel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change.
        /// </summary>
        internal static string Change {
            get {
                return ResourceManager.GetString("Change", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client initialization.
        /// </summary>
        internal static string ClientInitialization {
            get {
                return ResourceManager.GetString("ClientInitialization", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client has been initialized.
        /// </summary>
        internal static string ClientInitializationFinished {
            get {
                return ResourceManager.GetString("ClientInitializationFinished", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication started.
        /// </summary>
        internal static string CommunicationStarted {
            get {
                return ResourceManager.GetString("CommunicationStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Communication stopped.
        /// </summary>
        internal static string CommunicationStopped {
            get {
                return ResourceManager.GetString("CommunicationStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm.
        /// </summary>
        internal static string Confirm {
            get {
                return ResourceManager.GetString("Confirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connect.
        /// </summary>
        internal static string Connect {
            get {
                return ResourceManager.GetString("Connect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected devices.
        /// </summary>
        internal static string ConnectedDevices {
            get {
                return ResourceManager.GetString("ConnectedDevices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connected to REST service.
        /// </summary>
        internal static string ConnectedToRestService {
            get {
                return ResourceManager.GetString("ConnectedToRestService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connecting with service.
        /// </summary>
        internal static string ConnectingWithService {
            get {
                return ResourceManager.GetString("ConnectingWithService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current.
        /// </summary>
        internal static string Current {
            get {
                return ResourceManager.GetString("Current", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current data.
        /// </summary>
        internal static string CurrentData {
            get {
                return ResourceManager.GetString("CurrentData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collection interval.
        /// </summary>
        internal static string DataCollectInterval {
            get {
                return ResourceManager.GetString("DataCollectInterval", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data collection.
        /// </summary>
        internal static string DataCollection {
            get {
                return ResourceManager.GetString("DataCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data range.
        /// </summary>
        internal static string DataRange {
            get {
                return ResourceManager.GetString("DataRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Date.
        /// </summary>
        internal static string Date {
            get {
                return ResourceManager.GetString("Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device is not selected.
        /// </summary>
        internal static string DeviceIsNotSelected {
            get {
                return ResourceManager.GetString("DeviceIsNotSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device model.
        /// </summary>
        internal static string DeviceModel {
            get {
                return ResourceManager.GetString("DeviceModel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device name.
        /// </summary>
        internal static string DeviceName {
            get {
                return ResourceManager.GetString("DeviceName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Devices.
        /// </summary>
        internal static string Devices {
            get {
                return ResourceManager.GetString("Devices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnect.
        /// </summary>
        internal static string Disconnect {
            get {
                return ResourceManager.GetString("Disconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disconnected from REST service.
        /// </summary>
        internal static string DisconnectedToRestService {
            get {
                return ResourceManager.GetString("DisconnectedToRestService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download.
        /// </summary>
        internal static string Download {
            get {
                return ResourceManager.GetString("Download", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to log out from current session?.
        /// </summary>
        internal static string DoYouReallyWantToLogoutFromTheCurrentSession {
            get {
                return ResourceManager.GetString("DoYouReallyWantToLogoutFromTheCurrentSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you really want to delete the current selected report?.
        /// </summary>
        internal static string DoYouWantToDeleteCurrentReport {
            get {
                return ResourceManager.GetString("DoYouWantToDeleteCurrentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First name.
        /// </summary>
        internal static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Found.
        /// </summary>
        internal static string Found {
            get {
                return ResourceManager.GetString("Found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to From.
        /// </summary>
        internal static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gyroscope.
        /// </summary>
        internal static string Gyroscope {
            get {
                return ResourceManager.GetString("Gyroscope", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Humidity.
        /// </summary>
        internal static string Humidity {
            get {
                return ResourceManager.GetString("Humidity", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Information.
        /// </summary>
        internal static string Information {
            get {
                return ResourceManager.GetString("Information", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid date.
        /// </summary>
        internal static string InvalidDate {
            get {
                return ResourceManager.GetString("InvalidDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid login data.
        /// </summary>
        internal static string InvalidLoginData {
            get {
                return ResourceManager.GetString("InvalidLoginData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IP Address.
        /// </summary>
        internal static string IPAddress {
            get {
                return ResourceManager.GetString("IPAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last name.
        /// </summary>
        internal static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LED.
        /// </summary>
        internal static string LED {
            get {
                return ResourceManager.GetString("LED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lost.
        /// </summary>
        internal static string Lost {
            get {
                return ResourceManager.GetString("Lost", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lower range.
        /// </summary>
        internal static string LowerRange {
            get {
                return ResourceManager.GetString("LowerRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MAC Address.
        /// </summary>
        internal static string MACAddress {
            get {
                return ResourceManager.GetString("MACAddress", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Management.
        /// </summary>
        internal static string Management {
            get {
                return ResourceManager.GetString("Management", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum.
        /// </summary>
        internal static string Maximum {
            get {
                return ResourceManager.GetString("Maximum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure device.
        /// </summary>
        internal static string MeasureDevice {
            get {
                return ResourceManager.GetString("MeasureDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure duration.
        /// </summary>
        internal static string MeasureDuration {
            get {
                return ResourceManager.GetString("MeasureDuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure name.
        /// </summary>
        internal static string MeasureName {
            get {
                return ResourceManager.GetString("MeasureName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures.
        /// </summary>
        internal static string Measures {
            get {
                return ResourceManager.GetString("Measures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measures history.
        /// </summary>
        internal static string MeasuresHistory {
            get {
                return ResourceManager.GetString("MeasuresHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure start time.
        /// </summary>
        internal static string MeasureStartTime {
            get {
                return ResourceManager.GetString("MeasureStartTime", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Measure type.
        /// </summary>
        internal static string MeasureType {
            get {
                return ResourceManager.GetString("MeasureType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum.
        /// </summary>
        internal static string Minimum {
            get {
                return ResourceManager.GetString("Minimum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum {0} chars.
        /// </summary>
        internal static string MinimumChars {
            get {
                return ResourceManager.GetString("MinimumChars", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New.
        /// </summary>
        internal static string New {
            get {
                return ResourceManager.GetString("New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        internal static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No generated reports.
        /// </summary>
        internal static string NoGeneratedReports {
            get {
                return ResourceManager.GetString("NoGeneratedReports", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        internal static string NotLoggedIn {
            get {
                return ResourceManager.GetString("NotLoggedIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only integer values allowed.
        /// </summary>
        internal static string OnlyIntegerValuesAllowed {
            get {
                return ResourceManager.GetString("OnlyIntegerValuesAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter.
        /// </summary>
        internal static string Parameter {
            get {
                return ResourceManager.GetString("Parameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        internal static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Per unit.
        /// </summary>
        internal static string PerUnit {
            get {
                return ResourceManager.GetString("PerUnit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please type your data to login.
        /// </summary>
        internal static string PleaseTypeDataToLogIn {
            get {
                return ResourceManager.GetString("PleaseTypeDataToLogIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please wait.
        /// </summary>
        internal static string PleaseWait {
            get {
                return ResourceManager.GetString("PleaseWait", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to control led state.
        /// </summary>
        internal static string PressToControlLedState {
            get {
                return ResourceManager.GetString("PressToControlLedState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to delete current report.
        /// </summary>
        internal static string PressToDeleteCurrentReport {
            get {
                return ResourceManager.GetString("PressToDeleteCurrentReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to generate data.
        /// </summary>
        internal static string PressToGenerateData {
            get {
                return ResourceManager.GetString("PressToGenerateData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to login to app.
        /// </summary>
        internal static string PressToLoginToApp {
            get {
                return ResourceManager.GetString("PressToLoginToApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to logout current user.
        /// </summary>
        internal static string PressToLogoutCurrentUser {
            get {
                return ResourceManager.GetString("PressToLogoutCurrentUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to manage user accounts.
        /// </summary>
        internal static string PressToManageUserAccounts {
            get {
                return ResourceManager.GetString("PressToManageUserAccounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to move chart to left.
        /// </summary>
        internal static string PressToMoveChartToLeft {
            get {
                return ResourceManager.GetString("PressToMoveChartToLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to move chart to right.
        /// </summary>
        internal static string PressToMoveChartToRight {
            get {
                return ResourceManager.GetString("PressToMoveChartToRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to personalize app.
        /// </summary>
        internal static string PressToPersonalizeApp {
            get {
                return ResourceManager.GetString("PressToPersonalizeApp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to show devices list.
        /// </summary>
        internal static string PressToShowDevicesList {
            get {
                return ResourceManager.GetString("PressToShowDevicesList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to zoom chart.
        /// </summary>
        internal static string PressToZoomChart {
            get {
                return ResourceManager.GetString("PressToZoomChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Press to zoom out chart.
        /// </summary>
        internal static string PressToZoomOutChart {
            get {
                return ResourceManager.GetString("PressToZoomOutChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        internal static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report creator.
        /// </summary>
        internal static string ReportCreator {
            get {
                return ResourceManager.GetString("ReportCreator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Required field.
        /// </summary>
        internal static string RequiredField {
            get {
                return ResourceManager.GetString("RequiredField", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset.
        /// </summary>
        internal static string Reset {
            get {
                return ResourceManager.GetString("Reset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role.
        /// </summary>
        internal static string Role {
            get {
                return ResourceManager.GetString("Role", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Roles.
        /// </summary>
        internal static string Roles {
            get {
                return ResourceManager.GetString("Roles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run app on startup.
        /// </summary>
        internal static string RunAppOnStartup {
            get {
                return ResourceManager.GetString("RunAppOnStartup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Selected device.
        /// </summary>
        internal static string SelectedDevice {
            get {
                return ResourceManager.GetString("SelectedDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session end.
        /// </summary>
        internal static string SessionEnd {
            get {
                return ResourceManager.GetString("SessionEnd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session start.
        /// </summary>
        internal static string SessionStart {
            get {
                return ResourceManager.GetString("SessionStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sphere.
        /// </summary>
        internal static string Sphere {
            get {
                return ResourceManager.GetString("Sphere", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistic data.
        /// </summary>
        internal static string StatisticData {
            get {
                return ResourceManager.GetString("StatisticData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string Status {
            get {
                return ResourceManager.GetString("Status", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System architecture.
        /// </summary>
        internal static string SystemArchitecture {
            get {
                return ResourceManager.GetString("SystemArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to System version.
        /// </summary>
        internal static string SystemVersion {
            get {
                return ResourceManager.GetString("SystemVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Temperature.
        /// </summary>
        internal static string Temperature {
            get {
                return ResourceManager.GetString("Temperature", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is no connection with the device.
        /// </summary>
        internal static string ThereIsNoConnectionWithDevice {
            get {
                return ResourceManager.GetString("ThereIsNoConnectionWithDevice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        internal static string Time {
            get {
                return ResourceManager.GetString("Time", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data Collector.
        /// </summary>
        internal static string Title {
            get {
                return ResourceManager.GetString("Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to To.
        /// </summary>
        internal static string To {
            get {
                return ResourceManager.GetString("To", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Off.
        /// </summary>
        internal static string TurnOff {
            get {
                return ResourceManager.GetString("TurnOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to On.
        /// </summary>
        internal static string TurnOn {
            get {
                return ResourceManager.GetString("TurnOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated.
        /// </summary>
        internal static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upper range.
        /// </summary>
        internal static string UpperRange {
            get {
                return ResourceManager.GetString("UpperRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        internal static string User {
            get {
                return ResourceManager.GetString("User", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login history.
        /// </summary>
        internal static string UserLoginHistory {
            get {
                return ResourceManager.GetString("UserLoginHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name.
        /// </summary>
        internal static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User name has been already taken.
        /// </summary>
        internal static string UserNameIsTaken {
            get {
                return ResourceManager.GetString("UserNameIsTaken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        internal static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer.
        /// </summary>
        internal static string Viewer {
            get {
                return ResourceManager.GetString("Viewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visualization.
        /// </summary>
        internal static string Visualization {
            get {
                return ResourceManager.GetString("Visualization", resourceCulture);
            }
        }
    }
}
