//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollector.Client.UI.Collector {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="Collector.IMeasureCollectorService")]
    public interface IMeasureCollectorService {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeasureCollectorService/StartCollectingData", ReplyAction="http://tempuri.org/IMeasureCollectorService/StartCollectingDataResponse")]
        void StartCollectingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeasureCollectorService/StartCollectingData", ReplyAction="http://tempuri.org/IMeasureCollectorService/StartCollectingDataResponse")]
        System.Threading.Tasks.Task StartCollectingDataAsync();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeasureCollectorService/StopCollectingData", ReplyAction="http://tempuri.org/IMeasureCollectorService/StopCollectingDataResponse")]
        void StopCollectingData();
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IMeasureCollectorService/StopCollectingData", ReplyAction="http://tempuri.org/IMeasureCollectorService/StopCollectingDataResponse")]
        System.Threading.Tasks.Task StopCollectingDataAsync();
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IMeasureCollectorServiceChannel : DataCollector.Client.UI.Collector.IMeasureCollectorService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MeasureCollectorServiceClient : System.ServiceModel.ClientBase<DataCollector.Client.UI.Collector.IMeasureCollectorService>, DataCollector.Client.UI.Collector.IMeasureCollectorService {
        
        public MeasureCollectorServiceClient() {
        }
        
        public MeasureCollectorServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MeasureCollectorServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeasureCollectorServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MeasureCollectorServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public void StartCollectingData() {
            base.Channel.StartCollectingData();
        }
        
        public System.Threading.Tasks.Task StartCollectingDataAsync() {
            return base.Channel.StartCollectingDataAsync();
        }
        
        public void StopCollectingData() {
            base.Channel.StopCollectingData();
        }
        
        public System.Threading.Tasks.Task StopCollectingDataAsync() {
            return base.Channel.StopCollectingDataAsync();
        }
    }
}
