#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataCollector.Server.DataAccess.Context
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="DataCollectorDb")]
	public partial class StoredProceduresDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    #endregion
		
		public StoredProceduresDataContext() : 
				base(global::DataCollector.Server.DataAccess.Properties.Settings.Default.DataCollectorDbConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public StoredProceduresDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoredProceduresDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoredProceduresDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public StoredProceduresDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPU_GetSphereMeasurePoints")]
		public ISingleResult<SPU_GetSphereMeasurePointsResult> SPU_GetSphereMeasurePoints([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> deviceId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> to)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceId, type, from, to);
			return ((ISingleResult<SPU_GetSphereMeasurePointsResult>)(result.ReturnValue));
		}
		
		[global::System.Data.Linq.Mapping.FunctionAttribute(Name="dbo.SPU_GetMeasurePoints")]
		public ISingleResult<SPU_GetMeasurePointsResult> SPU_GetMeasurePoints([global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> deviceId, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="Int")] System.Nullable<int> type, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> from, [global::System.Data.Linq.Mapping.ParameterAttribute(DbType="DateTime")] System.Nullable<System.DateTime> to)
		{
			IExecuteResult result = this.ExecuteMethodCall(this, ((MethodInfo)(MethodInfo.GetCurrentMethod())), deviceId, type, from, to);
			return ((ISingleResult<SPU_GetMeasurePointsResult>)(result.ReturnValue));
		}
	}
	
	public partial class SPU_GetSphereMeasurePointsResult
	{
		
		private int _ID;
		
		private float _Point_X;
		
		private float _Point_Y;
		
		private float _Point_Z;
		
		private int _Type;
		
		private System.Nullable<int> _AssignedDeviceMeasureTimePoint_ID;
		
		private System.DateTime _TimeStamp;
		
		public SPU_GetSphereMeasurePointsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point_X", DbType="Real NOT NULL")]
		public float Point_X
		{
			get
			{
				return this._Point_X;
			}
			set
			{
				if ((this._Point_X != value))
				{
					this._Point_X = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point_Y", DbType="Real NOT NULL")]
		public float Point_Y
		{
			get
			{
				return this._Point_Y;
			}
			set
			{
				if ((this._Point_Y != value))
				{
					this._Point_Y = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Point_Z", DbType="Real NOT NULL")]
		public float Point_Z
		{
			get
			{
				return this._Point_Z;
			}
			set
			{
				if ((this._Point_Z != value))
				{
					this._Point_Z = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedDeviceMeasureTimePoint_ID", DbType="Int")]
		public System.Nullable<int> AssignedDeviceMeasureTimePoint_ID
		{
			get
			{
				return this._AssignedDeviceMeasureTimePoint_ID;
			}
			set
			{
				if ((this._AssignedDeviceMeasureTimePoint_ID != value))
				{
					this._AssignedDeviceMeasureTimePoint_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", DbType="DateTime NOT NULL")]
		public System.DateTime TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this._TimeStamp = value;
				}
			}
		}
	}
	
	public partial class SPU_GetMeasurePointsResult
	{
		
		private int _ID;
		
		private System.Nullable<float> _Value;
		
		private int _Type;
		
		private System.Nullable<int> _AssignedDeviceMeasureTimePoint_ID;
		
		private System.DateTime _TimeStamp;
		
		public SPU_GetMeasurePointsResult()
		{
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ID", DbType="Int NOT NULL")]
		public int ID
		{
			get
			{
				return this._ID;
			}
			set
			{
				if ((this._ID != value))
				{
					this._ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Value", DbType="Real")]
		public System.Nullable<float> Value
		{
			get
			{
				return this._Value;
			}
			set
			{
				if ((this._Value != value))
				{
					this._Value = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type", DbType="Int NOT NULL")]
		public int Type
		{
			get
			{
				return this._Type;
			}
			set
			{
				if ((this._Type != value))
				{
					this._Type = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_AssignedDeviceMeasureTimePoint_ID", DbType="Int")]
		public System.Nullable<int> AssignedDeviceMeasureTimePoint_ID
		{
			get
			{
				return this._AssignedDeviceMeasureTimePoint_ID;
			}
			set
			{
				if ((this._AssignedDeviceMeasureTimePoint_ID != value))
				{
					this._AssignedDeviceMeasureTimePoint_ID = value;
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_TimeStamp", DbType="DateTime NOT NULL")]
		public System.DateTime TimeStamp
		{
			get
			{
				return this._TimeStamp;
			}
			set
			{
				if ((this._TimeStamp != value))
				{
					this._TimeStamp = value;
				}
			}
		}
	}
}
#pragma warning restore 1591
